const Types = {
  GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
  GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
  CREATE_STUDENTS_REQUEST: 'CREATE_STUDENTS_REQUEST',
  DELETE_STUDENTS_REQUEST: 'DELETE_STUDENTS_REQUEST',
  UPDATE_STUDENTS_REQUEST: 'UPDATE_STUDENTS_REQUEST',
  STUDENT_ERROR: 'STUDENT_ERROR',
};

export default Types;
